apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-world
  labels:
    app: hello-world
    tier: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: demo
  template:
    metadata:
      labels:
        tier: demo
    spec:
      containers:
      - name: hello-world
        image: nginx:latest